### PR TITLE
feat: Make PromQL validation configurable

### PR DESCRIPTION
**Pull request by pbarsotti-glovo**
This PR makes the PromQL expression validation configurable so DataSources not compatible with Prometheus can be used.

### CODE REVIEW

**Comment by fgouteroux** [comment]
hi @pbarsotti-glovo, could you give more details about your use case ?

**Comment by pbarsotti-glovo** [comment]
> hi @pbarsotti-glovo, could you give more details about your use case ?

Hey, sure. We are using the provider to create alerts based on Loki and when we put a LogQL sentence (which is valid and works using the UI) we get errors due to the PromQL validation failing.

**Comment by fgouteroux** [comment]
> > hi @pbarsotti-glovo, could you give more details about your use case ?
> 
> Hey, sure. We are using the provider to create alerts based on Loki and when we put a LogQL sentence (which is valid and works using the UI) we get errors due to the PromQL validation failing.

This is interesting, do you have an alert example based on loki query result ?

**Comment by pbarsotti-glovo** [comment]
> > > hi @pbarsotti-glovo, could you give more details about your use case ?
> > 
> > 
> > Hey, sure. We are using the provider to create alerts based on Loki and when we put a LogQL sentence (which is valid and works using the UI) we get errors due to the PromQL validation failing.
> 
> This is interesting, do you have an alert example based on loki query result ?

Here is an example. Some fields are redacted but the structure is the same:

```
count(rate({cluster=~"***REDACTED***", job=~"integrations/kubernetes/eventhandler|***REDACTED***/eventrouter"} |= `202 FailedMount: MountVolume.SetUp failed for volume` | json | attributes_k8s_namespace_name = `***REDACTED***` [60m])) > 1
```

**Comment by fgouteroux** [comment]
Yes it's a LogQL expression, but how do you want to use this expr in mimir alert rule ? Why not use the [loki provider](https://registry.terraform.io/providers/fgouteroux/loki/latest) instead ?

**Comment by pbarsotti-glovo** [comment]
> Yes it's a LogQL expression, but how do you want to use this expr in mimir alert rule ? Why not use the [loki provider](https://registry.terraform.io/providers/fgouteroux/loki/latest) instead ?

Ahh, I didn't know about this provider. I will try to use it then.
Out curiosity, is there any strong reason to have 2 different providers using pretty much the same interface?

**Comment by fgouteroux** [comment]
> > Yes it's a LogQL expression, but how do you want to use this expr in mimir alert rule ? Why not use the [loki provider](https://registry.terraform.io/providers/fgouteroux/loki/latest) instead ?
> 
> Ahh, I didn't know about this provider. I will try to use it then. Out curiosity, is there any strong reason to have 2 different providers using pretty much the same interface?

I 've created the provider loki one year later mimir provider, so yes it's the same interface, but it's not the same product, the alert expr validation is different PromQL != LogQL, the release cycle too.

**Comment by pbarsotti-glovo** [comment]
> > > Yes it's a LogQL expression, but how do you want to use this expr in mimir alert rule ? Why not use the [loki provider](https://registry.terraform.io/providers/fgouteroux/loki/latest) instead ?
> > 
> > 
> > Ahh, I didn't know about this provider. I will try to use it then. Out curiosity, is there any strong reason to have 2 different providers using pretty much the same interface?
> 
> I 've created the provider loki one year later after mimir provider, so yes it's the same interface, but it's not the same product, the alert expr validation is different PromQL != LogQL, the release cycle too.

Yeah, I'm new to this Grafana world, so probably I don't know about how the ecosystem evolved over time, but to me this looks like a common alerting interface that works with multiple datasources, each one with different characteristics (expr lang, target APIs, etc).
In any case, thanks for replying and for creating these provider in the first place! I'll close this PR and try with the other provider.

**Pull request closed without merging**
