### PR TITLE
chore: Bump prometheus version

### PR DESCRIPTION
**Pull request by pbarsotti-glovo**
PromQL validation fails to parse a valid query due to unknown function:

`Error: "rule.0.expr": Invalid PromQL expression "avg by (task_name) (histogram_avg(rate(REDACTED}[1m]))) > 30000": 1:21: parse error: unknown function with name "histogram_avg"`

Looks like this was added in version 2.53.0 (0.53.0) [here](https://github.com/prometheus/prometheus/commit/6feffeb92e36b064a53d2283e50d6db355c95cb0).

### CODE REVIEW

**Comment by fgouteroux** [comment]
@pbarsotti-glovo Could you please add a test case for the `histogram_avg` function ?

**Comment by pbarsotti-glovo** [comment]
> @pbarsotti-glovo Could you please add a test case for the `histogram_avg` function ?

Sure! Added. Let me know if that's enough for you. Thanks.

**Comment by fgouteroux** [comment]
@pbarsotti-glovo could you a check like [here](https://github.com/fgouteroux/terraform-provider-mimir/blob/main/mimir/resource_mimir_alertmanager_config_test.go#L1064-L1070) to skip this test for mimir version < 2.12 ?

**Review by fgouteroux — APPROVED** [review]

**Comment by pbarsotti-glovo** [comment]
Hey @fgouteroux sorry to bother you again... how the release cycle works? Do you release on demand or following a schedule? Thansk!

**Comment by fgouteroux** [comment]
> Hey @fgouteroux sorry to bother you again... can you tell me how the release cycle works? Do you release on demand or following a schedule? Thansk!

I have no schedule, sometimes I group other updates before releasing, it depends of my busy time.

**Comment by fgouteroux** [comment]
@pbarsotti-glovo released version [1.0.2](https://github.com/fgouteroux/terraform-provider-mimir/releases/tag/v1.0.2)

**Comment by pbarsotti-glovo** [comment]
> @pbarsotti-glovo released version [1.0.2](https://github.com/fgouteroux/terraform-provider-mimir/releases/tag/v1.0.2)

Many thanks @fgouteroux!

**Pull request merged**
