### PR TITLE
feat: add mimir_distributor_tenant_stats datasource

### PR DESCRIPTION
**Pull request by adnankobir**
Adds `mimir_distributor_tenant_stats` datasource to query tenant stats. Currently this is the only endpoint that provides break down of all tenants and associated stats.

Example output:
```tf
data.mimir_distributor_tenant_stats.this: Reading...
data.mimir_distributor_tenant_stats.this: Read complete after 0s [id=2230098833]

Changes to Outputs:
  + stats = {
      + id    = "2230098833"
      + stats = [
          + {
              + api_ingest_rate   = 1997.65
              + rule_ingest_rate  = 0
              + series            = 2151
              + total_ingest_rate = 1997.65
              + user              = "mongodb"
            },
        ]
      + user  = "mongodb"
    }

You can apply this plan to save these new output values to the Terraform state, without changing any real infrastructure.
```

### CODE REVIEW

**Comment by adnankobir** [comment]
@fgouteroux might need a little help with these tests, thanks!

**Comment by fgouteroux** [comment]
@adnankobir I'm not sure to see how this datasource could be helpful, as theses stats are dynamics. Maybe you can explain your use case.

**Comment by fgouteroux** [comment]
@adnankobir Ok, it make senses. Maybe it will be better to work with json instead of html, so I think a PR to [mimir](https://github.com/grafana/mimir) could be accepted. Otherwise, I think we could go with it for now. Let me check about failing tests first, I have some issues with many concurrent call to the rule group api.

**Comment by fgouteroux** [comment]
@adnankobir after a quick check you can get theses stats in json.
https://github.com/grafana/mimir/blob/main/pkg/distributor/http_admin.go#L51

You need to pass the header `Accept: json`  and you will get a json response.

**Comment by adnankobir** [comment]
> @adnankobir after a quick check you can get theses stats in json. https://github.com/grafana/mimir/blob/1593dafe750985071fac46f610654cb9167cdf4b/pkg/distributor/http_admin.go#L51-L57
> 
> You need to pass the header `Accept: json` and you will get a json response.
> 
> NB: replication factor stat is not available in json response

great find! I relied on the documentation and this wasn't mentioned 😞 . Will refactor this, but I suppose we can just document the fact that replication factor isn't taken into account!

**Comment by fgouteroux** [comment]
> > @adnankobir after a quick check you can get theses stats in json. https://github.com/grafana/mimir/blob/1593dafe750985071fac46f610654cb9167cdf4b/pkg/distributor/http_admin.go#L51-L57
> > You need to pass the header `Accept: json` and you will get a json response.
> > NB: replication factor stat is not available in json response
> 
> great find! I relied on the documentation and this wasn't mentioned 😞 . Will refactor this, but I suppose we can just document the fact that replication factor isn't taken into account!

Yes, the replication factor is not helpful compared to your use case.

**Comment by adnankobir** [comment]
@fgouteroux updated.

**Review by fgouteroux — CHANGES_REQUESTED** [review]

**Comment by adnankobir** [comment]
@fgouteroux updated, please lmk.

**Review by fgouteroux — APPROVED** [review]

**Comment by fgouteroux** [comment]
@adnankobir LGTM, thanks

**Comment by fgouteroux** [comment]
@adnankobir released in [v0.2.3](https://github.com/fgouteroux/terraform-provider-mimir/releases/tag/v0.2.3)

**Pull request merged**
