### PR TITLE
Fix schema for update_alerts

### PR DESCRIPTION
**Pull request by gburanov**

### CODE REVIEW

**Comment by gburanov** [comment]
Currently this provider does not work for opsgenie. Here is potential fix

**Comment by fgouteroux** [comment]
Thanks for reporting this. I will have a look.

**Comment by fgouteroux** [comment]
Thanks @gburanov

**Comment by gburanov** [comment]
@fgouteroux  can u please release new version in `registry.terraform.io`? then we can just update version and use it!

**Comment by fgouteroux** [comment]
> @fgouteroux can u please release new version in `registry.terraform.io`? then we can just update version and use it!

@gburanov [New release 0.0.7 available](https://registry.terraform.io/providers/fgouteroux/mimir/0.0.7)

**Pull request merged**
