### PR TITLE
feat: query_offset replaces evaluation_delay in Mimir 2.13

### PR DESCRIPTION
**Pull request by dracoyunho**
# Summary

#39 added `evaluation_delay` with the knowledge that Mimir 2.13 would upgrade Prometheus such that the setting would be deprecated in favour of `query_offset`; that change has been made and Mimir 2.13 is now generally available.

(I did a mass replace for `evaluation_delay` with `query_offset` and `EvaluationDelay` with `QueryOffset`.)

The test version is updated to `2.13.0`, correspondingly.

### CODE REVIEW

**Comment by fgouteroux** [comment]
hi @dracoyunho

It 's deprecated in mimir 2.13, so we need to keep a consistency also in this provider.

I suggest to add `query_offset` as a new attribute and to make `evaluation_delay` as deprecated attribute like recommended here: https://developer.hashicorp.com/terraform/plugin/sdkv2/best-practices/deprecations#renaming-an-optional-attribute

Then when mimir will remove completely this attribute, we will remove it too.

**Review by fgouteroux — CHANGES_REQUESTED** [review]
We need to keep almost two minor version for the compatibility

**Review by fgouteroux — COMMENTED** [review]
It seems that the CI failed with this change

**Comment by dracoyunho** [comment]
`/bin/sh` seems to be not available as a cmd in 2.13.0

Going to see if there's a fix for that

**Comment by fgouteroux** [comment]
Thx @dracoyunho. I will change the entrypoint command and only pass arguments, since image changed to distroless.

**Pull request merged**
